### PR TITLE
add similar projects [SideBand, MeshChat]

### PR DESCRIPTION
**Pull request by xa4hf8**
https://reticulum.network/
https://www.unsigned.io/website/rnode/

### CODE REVIEW

**Comment by mwarning** [comment]
not sure if these are similar projects. These are not a telephone capable app and do not use IP, but use their own networking stack.

**Comment by xa4hf8** [comment]
While [iOS is not supported due to platform restrictions](https://github.com/markqvist/Sideband/issues/19), Sideband does run on Android phones and is available [here](https://github.com/markqvist/Sideband/releases).  It can also be auto-updated by adding the repo to [Obtainium](https://f-droid.org/en/packages/dev.imranr.obtainium.fdroid/).

I thought these two apps were similar enough to qualify because they support WiFi and do not require provisioning.  External hardware is not an explicit requirement, but substantially improves the usefulness, reliability and extensibility of ad-hoc Reticulum networks.  The Android app supports tunneling & relaying traffic over TCP/IP connections, so people with internet connectivity can serve as a bridge between Reticulum groups that could otherwise not communicate.  This scalability and support for external transport media is essential if you want to form a large user base and become a popular standard.  To that end, Reticulum can employ any form of wired or wireless transport (including LASER driven through a serial port.)  For more information, please see the “Guide” tab in the app.

**Comment by mwarning** [comment]
I will add a link to Sideband, since it allows audio messages.

**Comment by xa4hf8** [comment]
no problem, best regards 👍

**Comment by mwarning** [comment]
Likewise :)

**Comment by mwarning** [comment]
I have found apps that are more similar to Meshenger and added those.

**Pull request closed without merging**
