### PR TITLE
Renaming underscore variables to CamelCase

### LINKED ISSUE #75: Rename variables from underscore to CamelCase
Kotlin (or rather Android Studio) complains about local varaibles that have underscores.
All such variables need to be renamed. E.g. "new_from" => "newFrom"

### PR DESCRIPTION
**Pull request by adicoder95**
closes #75 
@mwarning I renamed all the variables to camel case so we don't get warnings further.

### CODE REVIEW

**Comment by mwarning** [comment]
Please remove the remaining import changes (`git reset` and `git add -p` might help here). Also change the commit miessage to include a topic, e.g. `global: rename variables to camel case` (`git commit --amend` will let you do this).

Sorry for all the extra effort, but kowning `git` will help you a lot here.

**Comment by adicoder95** [comment]
@mwarning that command didn't work

**Comment by mwarning** [comment]
Look up example on a the Internet first on how to use these commands. They also need arguments.

**Comment by adicoder95** [comment]
am gonna take a course on getting started with git and GitHub by google on coursera, once I get a bit free from all this

**Pull request closed without merging**
